### ISSUE TITLE
the linux npm package for the cs-cli does not work correctly

### ISSUE THREAD

**Issue by chronical** [CloudSlang/cloudslang-cli#6]
It seems that there are three issues with the linux npm package:
- has not been updated on the remote repo since version  0.9.60.0 (current version 1.x)
- can't find a way to also fetch the content part with this method
- after install on a linux machine, the main symlink is pointing to the windows batch script 

repro steps:
whereis cslang
cslang: /usr/bin/cslang

ll /usr/bin/cslang
lrwxrwxrwx 1 root root 55 Jun 22 23:55 /usr/bin/cslang -> ../lib/node_modules/cloudslang-cli/run_cslang_batch.**bat**

it should instead point to: /usr/lib/node_modules/cloudslang-cli/cloudslang-cli/cslang-cli/bin/cslang

@Bonczidai @victorursan @andreivasiletruta @tethryus @StefanCristian

**Comment by andreivasiletruta** [comment]
@chronical I suggest we split the content part of the issue for the remaining work that needs to be done and make sure to link this issue with the new pull request you've submitted.

**Comment by chronical** [comment]
done, added issue #11 for that 

all the other items have been addressed with pull request https://github.com/CloudSlang/cs-npm/commit/8834184b68a1450618ff208055193a6f59629efe
